# Generated by Django 5.2.3 on 2026-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_images/'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_images/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
